### PR TITLE
[WIP] Implementation for Erlang maps

### PR DESCRIPTION
**Pull request by filmor**
Still missing:

- [ ] Tests
- [ ] Matching
- [x] Some individual methods
- [x] Reformatting to match the project's style
- [x] Revert changes to `NFX.csproj`

Decoding works already, though.

### CODE REVIEW

**Comment by saleyn** [comment]
This looks great.
In ErlMap.cs please move "Dictionary<IErlObject, IErlObject> _items;" to the private region, and rename the member to "m_Items" to match the project's coding style.

**Comment by filmor** [comment]
I saw in another file that you are apparently using 4 spaces indents on namespaces and 2 on everything else. Is that really the plan?!

**Comment by saleyn** [comment]
The current plan is to use 2 spaces across the board, but there may be some legacy leftovers to be fixed.

**Comment by saleyn** [comment]
One more thing - why are the changes to Source/NFX/NFX.csproj needed?

**Comment by filmor** [comment]
They are not needed, I had to do them to get this running in my Visual Studio installation and committed them by accident. I'll remove them as soon as I'm done.

**Comment by saleyn** [comment]
Please squash your commits.

**Comment by filmor** [comment]
I did just now, but you can nowadays just do that on merge.

**Comment by saleyn** [comment]
Thank you for your contribution!

**Pull request merged**
