### PR TITLE
add flag UTF8Atom in enum NodeCompatibility

### PR DESCRIPTION
**Pull request by dbegunkov**
Please review. This fix allow connect to Erlang 20. Thank you!

### CODE REVIEW

**Comment by saleyn** [comment]
This makes sense, however, I doubt this single change is sufficient for proper support of UTF8 atom feature in v20 of Erlang.  Is it?

**Comment by dbegunkov** [comment]
Yes! This commit is only allows connect to erlang 20 from NXF.Elang

**Comment by stchar** [comment]
Hi. awesome fix. thanks.

@saleyn 
When it will be available in the public nuget repository? 
I mean https://www.nuget.org/packages/NFX.Erlang/
Are you a maintaier&

**Comment by itadapter** [comment]
@stchar @saleyn @dbegunkov 
We are pushing the update to nuget later today,
on a separate note, we are moving this into NFXv5 which is 100% Net Standards based, so it works
natively on Linux and Mac via .Net Core and performance is stellar (better than .NET framework 10-15%)

so check back tomorrow and stay tuned for NFX v5 within 5 days.

**Pull request merged**
